name: Build
run-name: Build image, deploy on k8s and run deploy tests
on: ["pull_request"]
env:
  IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/app:${{ github.sha }}
  USERNAME: ${{ github.actor }}
  PASSWORD: ${{ secrets.GHCR_TOKEN }}
jobs:
  BuildAndPushDockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $USERNAME
          password: $PASSWORD
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $IMAGE_REPO
          name: Build and push 
  DeployOnK8s:
    runs-on: ubuntu-latest
    # Depends on previous job's Docker image
    needs: [BuildAndPushDockerImage]
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Deploy Application
        run: |
          kubectl create secret docker-registry ghcr-token \
          --docker-username=${{ $USERNAME }} \
          --docker-password=${{ $PASSWORD }} \
          --docker-server=ghcr.io
          envsubst < k8s/app-deploy.yaml | kubectl apply -f -
          kubectl wait pods --for condition=Ready --timeout=90s --all
          kubectl expose deployment/rps-deployment --type=NodePort --port 8080 --target-port 5000
      - name: Test Deployment
        run: |
          export NODE_PORT=$(kubectl get services/rps-deployment -o go-template='{{(index .spec.ports 0).nodePort}}')
          echo NODE_PORT=${NODE_PORT}
          kubectl describe services/rps-deployment
          export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
          kubectl exec $POD_NAME -- curl localhost:5000/health
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd
