name: Workflow1
run-name: Run push checks
on: []
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pip install -r requirements.txt --upgrade pip
      - run: pylint src tests
      - run: black --check src tests
      - run: PYTHONPATH="${PYTHONPATH}:src" pytest tests