name: lint-format-tests
run-name: Run push checks
on: ["push"]
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pip install -r requirements.txt --upgrade pip
      - name: Run linter
        run: pylint src tests
      - name: Run formatter
        run: black --check src tests
      - name: Run pytest
        run: PYTHONPATH="${PYTHONPATH}:src" coverage run -m pytest tests/unit tests/functional
      - name: Generate coverage report
        run: coverage report